"""storage imple8

Revision ID: 0753a97a6fe1
Revises: 57515bdcd093
Create Date: 2024-02-08 14:13:11.084312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0753a97a6fe1'
down_revision = '57515bdcd093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
