"""initial12

Revision ID: 0771f5370c2b
Revises: d1459152c927
Create Date: 2024-02-06 21:40:46.431705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0771f5370c2b'
down_revision = 'd1459152c927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
