"""initial

Revision ID: 0a50426933dd
Revises: 
Create Date: 2024-02-05 21:17:27.051756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a50426933dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('criteriaName', sa.String(length=100), nullable=False))
    op.drop_index('criteiaName', table_name='criteria')
    op.create_unique_constraint(None, 'criteria', ['criteriaName'])
    op.drop_column('criteria', 'criteiaName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('criteiaName', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'criteria', type_='unique')
    op.create_index('criteiaName', 'criteria', ['criteiaName'], unique=False)
    op.drop_column('criteria', 'criteriaName')
    # ### end Alembic commands ###
