"""storage imple6

Revision ID: 1eb54776c566
Revises: 53d13346ca3e
Create Date: 2024-02-08 12:23:03.961000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb54776c566'
down_revision = '53d13346ca3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
