"""storage imple9

Revision ID: 261cbd97315d
Revises: f30cb3c9f8f2
Create Date: 2024-02-08 14:37:19.585680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261cbd97315d'
down_revision = 'f30cb3c9f8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
