"""storage imple3

Revision ID: 2ac7a939ff19
Revises: 7051cd3ea3f4
Create Date: 2024-02-07 13:44:45.959714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac7a939ff19'
down_revision = '7051cd3ea3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
