"""initial9

Revision ID: 2b3be7cac96d
Revises: 9d60516246b1
Create Date: 2024-02-06 20:47:35.421023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3be7cac96d'
down_revision = '9d60516246b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'alternative_value', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative', ['user_id'], ['id'])
    # ### end Alembic commands ###
