"""storage imple7

Revision ID: 2c6886d7a277
Revises: c9e6284b231c
Create Date: 2024-02-08 13:06:53.413508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6886d7a277'
down_revision = 'c9e6284b231c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
