"""initial3

Revision ID: 37317a83cfdb
Revises: 4bf2b7feed2a
Create Date: 2024-02-05 22:11:57.190142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37317a83cfdb'
down_revision = '4bf2b7feed2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('criteria_name', sa.String(length=100), nullable=False))
    op.drop_constraint('alternative_value_ibfk_2', 'alternative_value', type_='foreignkey')
    op.drop_column('alternative_value', 'criteria_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('criteria_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('alternative_value_ibfk_2', 'alternative_value', 'criteria', ['criteria_id'], ['id'])
    op.drop_column('alternative_value', 'criteria_name')
    # ### end Alembic commands ###
