"""storage imple16

Revision ID: 40cda86fce1d
Revises: 437d2ade31b1
Create Date: 2024-02-08 15:50:46.851574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cda86fce1d'
down_revision = '437d2ade31b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
