"""storage imple15

Revision ID: 437d2ade31b1
Revises: 92ee7e934d11
Create Date: 2024-02-08 15:41:33.649781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437d2ade31b1'
down_revision = '92ee7e934d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
