"""initial3

Revision ID: 4bf2b7feed2a
Revises: 8dcc9e0bb1c7
Create Date: 2024-02-05 22:04:33.579638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bf2b7feed2a'
down_revision = '8dcc9e0bb1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('criteria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alternative_value', 'criteria', ['criteria_id'], ['id'])
    op.drop_column('alternative_value', 'criteria_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('criteria_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'alternative_value', type_='foreignkey')
    op.drop_column('alternative_value', 'criteria_id')
    # ### end Alembic commands ###
