"""storage imple13

Revision ID: 4d8c5b756f18
Revises: aa30d685c233
Create Date: 2024-02-08 15:00:53.278153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d8c5b756f18'
down_revision = 'aa30d685c233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternative_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_value',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alternative_value', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('criteria_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
