"""storage imple5

Revision ID: 53d13346ca3e
Revises: 92b792b25099
Create Date: 2024-02-08 12:09:10.118164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d13346ca3e'
down_revision = '92b792b25099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
