"""storage imple7

Revision ID: 57515bdcd093
Revises: 2c6886d7a277
Create Date: 2024-02-08 14:12:57.313047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57515bdcd093'
down_revision = '2c6886d7a277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
