"""initial10

Revision ID: 5c2841e8a515
Revises: 2b3be7cac96d
Create Date: 2024-02-06 21:13:30.292772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2841e8a515'
down_revision = '2b3be7cac96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'alternative_value', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative_value', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
