"""storage imple10

Revision ID: 6d3e90d49039
Revises: 261cbd97315d
Create Date: 2024-02-08 14:37:31.745865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3e90d49039'
down_revision = '261cbd97315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
