"""storage imple2

Revision ID: 7051cd3ea3f4
Revises: b406e4d7acfc
Create Date: 2024-02-07 13:36:04.683401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7051cd3ea3f4'
down_revision = 'b406e4d7acfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
