"""initial5

Revision ID: 7b244b9c3c4e
Revises: b539b7ba2311
Create Date: 2024-02-06 15:45:56.291447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b244b9c3c4e'
down_revision = 'b539b7ba2311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
