"""initial7

Revision ID: 80f79ce4defc
Revises: cd0f3fc3fa99
Create Date: 2024-02-06 20:37:47.039797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80f79ce4defc'
down_revision = 'cd0f3fc3fa99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'alternative', ['user'], ['id'])
    op.drop_column('result', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative', ['user_id'], ['id'])
    op.drop_column('result', 'user')
    # ### end Alembic commands ###
