"""initial1

Revision ID: 81e286ccdacd
Revises: 0a50426933dd
Create Date: 2024-02-05 21:19:57.162558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81e286ccdacd'
down_revision = '0a50426933dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=True),
    sa.Column('criteria_name', sa.String(length=100), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternative.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alternative', sa.Column('criteria_name', sa.String(length=100), nullable=False))
    op.drop_index('criteriaName', table_name='alternative')
    op.create_unique_constraint(None, 'alternative', ['criteria_name'])
    op.drop_column('alternative', 'CriteriaValues')
    op.drop_column('alternative', 'criteriaName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative', sa.Column('criteriaName', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('alternative', sa.Column('CriteriaValues', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'alternative', type_='unique')
    op.create_index('criteriaName', 'alternative', ['criteriaName'], unique=False)
    op.drop_column('alternative', 'criteria_name')
    op.drop_table('alternative_value')
    # ### end Alembic commands ###
