"""storage imple14

Revision ID: 85a9127a5d53
Revises: 4d8c5b756f18
Create Date: 2024-02-08 15:07:48.448492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a9127a5d53'
down_revision = '4d8c5b756f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative', sa.Column('alternative_value', sa.String(length=5000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alternative', 'alternative_value')
    # ### end Alembic commands ###
