"""initial2

Revision ID: 8dcc9e0bb1c7
Revises: 81e286ccdacd
Create Date: 2024-02-05 22:03:59.072725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcc9e0bb1c7'
down_revision = '81e286ccdacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
