"""storage imple4

Revision ID: 92b792b25099
Revises: 2ac7a939ff19
Create Date: 2024-02-07 13:47:14.151474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92b792b25099'
down_revision = '2ac7a939ff19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('criteriaName', sa.String(length=100), nullable=False))
    op.drop_column('criteria', 'criteiaName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('criteiaName', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('criteria', 'criteriaName')
    # ### end Alembic commands ###
