"""storage imple14

Revision ID: 92ee7e934d11
Revises: 85a9127a5d53
Create Date: 2024-02-08 15:15:11.906912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92ee7e934d11'
down_revision = '85a9127a5d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative', sa.Column('criteria_values', sa.String(length=5000), nullable=False))
    op.drop_column('alternative', 'alternative_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative', sa.Column('alternative_value', mysql.VARCHAR(length=5000), nullable=False))
    op.drop_column('alternative', 'criteria_values')
    # ### end Alembic commands ###
