"""initial8

Revision ID: 9d60516246b1
Revises: 80f79ce4defc
Create Date: 2024-02-06 20:43:18.142892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d60516246b1'
down_revision = '80f79ce4defc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'alternative', ['user_id'], ['id'])
    op.drop_column('result', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative', ['user'], ['id'])
    op.drop_column('result', 'user_id')
    # ### end Alembic commands ###
