"""storage imple7

Revision ID: a61c0a7d9803
Revises: 1eb54776c566
Create Date: 2024-02-08 12:42:25.571846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61c0a7d9803'
down_revision = '1eb54776c566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
