"""storage imple12

Revision ID: aa30d685c233
Revises: d05486e93f9d
Create Date: 2024-02-08 14:57:21.399780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa30d685c233'
down_revision = 'd05486e93f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alternative_value_ibfk_1', 'alternative_value', type_='foreignkey')
    op.drop_column('alternative_value', 'user_id')
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.drop_column('result', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative', ['user_id'], ['id'])
    op.add_column('alternative_value', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('alternative_value_ibfk_1', 'alternative_value', 'alternative', ['user_id'], ['id'])
    # ### end Alembic commands ###
