"""storage imple1

Revision ID: b406e4d7acfc
Revises: 35c969763ef1
Create Date: 2024-02-07 13:22:54.508907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b406e4d7acfc'
down_revision = '35c969763ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative', sa.Column('criteria_name', sa.String(length=100), nullable=False))
    op.drop_index('criteriaName', table_name='alternative')
    op.drop_column('alternative', 'criteriaName')
    op.drop_column('alternative', 'CriteriaValues')
    op.drop_column('alternative', 'updated_at')
    op.drop_column('alternative', 'created_at')
    op.drop_column('alternative_value', 'updated_at')
    op.drop_index('criteiaName', table_name='criteria')
    op.drop_column('criteria', 'updated_at')
    op.drop_column('result', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('criteria', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.create_index('criteiaName', 'criteria', ['criteiaName'], unique=False)
    op.add_column('alternative_value', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('alternative', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('alternative', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('alternative', sa.Column('CriteriaValues', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('alternative', sa.Column('criteriaName', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('criteriaName', 'alternative', ['criteriaName'], unique=False)
    op.drop_column('alternative', 'criteria_name')
    # ### end Alembic commands ###
