"""initial4

Revision ID: b539b7ba2311
Revises: c969f2734c39
Create Date: 2024-02-06 15:33:51.590294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b539b7ba2311'
down_revision = 'c969f2734c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
