"""initial13

Revision ID: c24e70a15827
Revises: 0771f5370c2b
Create Date: 2024-02-06 21:57:13.816470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24e70a15827'
down_revision = '0771f5370c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_ibfk_1', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'alternative', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_ibfk_1', 'result', 'alternative_value', ['user_id'], ['id'])
    # ### end Alembic commands ###
