"""initial3

Revision ID: c881c1022843
Revises: 37317a83cfdb
Create Date: 2024-02-06 07:03:03.556167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c881c1022843'
down_revision = '37317a83cfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('criteria_name', table_name='alternative')
    op.drop_index('criteriaName', table_name='criteria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('criteriaName', 'criteria', ['criteriaName'], unique=False)
    op.create_index('criteria_name', 'alternative', ['criteria_name'], unique=False)
    # ### end Alembic commands ###
