"""initial4

Revision ID: c969f2734c39
Revises: c881c1022843
Create Date: 2024-02-06 15:29:26.951987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c969f2734c39'
down_revision = 'c881c1022843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('alternative_value', sa.Column('alternative_value', sa.Integer(), nullable=False))
    op.drop_constraint('alternative_value_ibfk_1', 'alternative_value', type_='foreignkey')
    op.create_foreign_key(None, 'alternative_value', 'alternative', ['user_id'], ['id'])
    op.drop_column('alternative_value', 'criteria_value')
    op.drop_column('alternative_value', 'alternative_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_value', sa.Column('alternative_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alternative_value', sa.Column('criteria_value', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alternative_value', type_='foreignkey')
    op.create_foreign_key('alternative_value_ibfk_1', 'alternative_value', 'alternative', ['alternative_id'], ['id'])
    op.drop_column('alternative_value', 'alternative_value')
    op.drop_column('alternative_value', 'user_id')
    # ### end Alembic commands ###
