"""storage imple7

Revision ID: c9e6284b231c
Revises: a61c0a7d9803
Create Date: 2024-02-08 12:47:15.814418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e6284b231c'
down_revision = 'a61c0a7d9803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
