"""storage imple8

Revision ID: ce88e9397aa7
Revises: 0753a97a6fe1
Create Date: 2024-02-08 14:24:54.702482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce88e9397aa7'
down_revision = '0753a97a6fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
