"""storage imple11

Revision ID: d05486e93f9d
Revises: 6d3e90d49039
Create Date: 2024-02-08 14:51:11.931165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05486e93f9d'
down_revision = '6d3e90d49039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
