"""initial11

Revision ID: d1459152c927
Revises: 5c2841e8a515
Create Date: 2024-02-06 21:20:15.343691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1459152c927'
down_revision = '5c2841e8a515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
