"""storage imple9

Revision ID: f30cb3c9f8f2
Revises: d36050ea5691
Create Date: 2024-02-08 14:25:33.718713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30cb3c9f8f2'
down_revision = 'd36050ea5691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
